Repository nt14-space-odyssey/Space-Odyssey-1, pull requests merged in 2025-03, with the labels that each got.

#12 Удаление научного скафандра
  Resources/Prototypes/_ByLoks/ScienceHardsuit.yml
Labels: Changes: No C#

#13 logo
  Resources/Textures/Logo/logo-ru.png
  Resources/Textures/Logo/logo.png
  Resources/Textures/Logo/logo.svg
Labels: Changes: No C#

#14 shaman
  Resources/Audio/_Odyssey/shaman.ogg
  Resources/Prototypes/_Odyssey/Entities/Mobs/shaman.yml
  Resources/Textures/_Odyssey/shaman.rsi/meta.json
  Resources/Textures/_Odyssey/shaman.rsi/shaman.png
Labels: Changes: No C#, Changes: Sprites, Changes: Audio

#17 Наркотики, фикс билда и многое другое!
  Resources/Locale/ru-RU/reagents/meta/toxins.ftl
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Hydroponics/seeds.yml
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/_Odyssey/Reagents/narcotics.yml
  Resources/Prototypes/_Odyssey/dino.yml
Labels: Changes: No C#, Changes: Localization

#20 удалены роли шахтёра с карт
  Resources/Prototypes/Corvax/Maps/Corvax/astra.yml
  Resources/Prototypes/Corvax/Maps/Corvax/avrite.yml
  Resources/Prototypes/Corvax/Maps/Corvax/awesome.yml
  Resources/Prototypes/Corvax/Maps/Corvax/delta.yml
  Resources/Prototypes/Corvax/Maps/Corvax/frame.yml
  Resources/Prototypes/Corvax/Maps/Corvax/gelta.yml
  Resources/Prototypes/Corvax/Maps/Corvax/glacier.yml
  Resources/Prototypes/Corvax/Maps/Corvax/ishimura.yml
  Resources/Prototypes/Corvax/Maps/Corvax/maus.yml
  Resources/Prototypes/Corvax/Maps/Corvax/outpost.yml
  Resources/Prototypes/Corvax/Maps/Corvax/paper.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pearl.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pilgrim.yml
  Resources/Prototypes/Corvax/Maps/Corvax/silly.yml
  Resources/Prototypes/Corvax/Maps/Corvax/split.yml
  Resources/Prototypes/Corvax/Maps/Corvax/terra.yml
  Resources/Prototypes/Corvax/Maps/Corvax/tushkan.yml
  Resources/Prototypes/Maps/amber.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/convex.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/debug.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/oasis.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/reach.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Maps/train.yml
Labels: Changes: No C#, Changes: Map

#21 Make aghosts great again!
  Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_Odyssey/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/_Odyssey/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Odyssey/Reagents/narcotics.yml
Labels: Changes: No C#

#19 Update DefaultRules.xml
  Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
Labels: Changes: No C#

#18 Update AI station texture
  Resources/Textures/Mobs/Silicon/station_ai.rsi/ai.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/ai_camera.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/ai_dead.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/ai_empty.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/base.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/default.png
  Resources/Textures/Mobs/Silicon/station_ai.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites
